kccistc/intel-05

class01/README.md
class02/README.md

class01-hw3-hantaeseop

---

class01/README.md
class02/README.md

* Compare branch : class01-hw3-jsh
* Base Branch : `main`
* Reviewer : J-WBaek

[Class01 HW#3] Github PR 실습 - Table 수정 <정상훈>

---

class01/README.md
class02/README.md

* Compare branch : class01-hw3-egk
* Base Branch : `main`
* Reviewer : JWBaek

[Class01 HW#3] Github PR 실습 - Table 수정 <고의근> 

---

class01/README.md
class02/README.md

[장성민] [Class01 HW#3] Github PR 실습 - Table 수정

[장성민] [Class01 HW#3] Github PR 실습 - Table 수정

---

class01/README.md
class02/README.md

[Class01 HW#3] Github PR 실습 - Table 수정

[Class01 HW#3] Github PR 실습 - Table 수정 윤태준

---

class01/README.md
class02/README.md

Class01 GitHub 과제를 위한 issue 입니다.

[Class01 HW#3] Github PR 실습 - Table 수정 - 박준수

---

class01/README.md
class02/README.md

Compare branch : class01-hw3-jth

[Class01 HW#3] Github PR 실습 - Table 수정 <정태현>

---

class01/README.md
class02/README.md

[Class01 HW#3] Github PR 실습 - 최재원

---

class01/README.md
class02/README.md

[박정우][Class01 HW#3] Github PR 실습 - Table 수정

---

class01/README.md
class02/README.md

the 2nd homework

---

class01/homework/JHChoi/hw4_pythonHW_and_math/HW4_GD.py
class01/homework/JHChoi/hw4_pythonHW_and_math/HW4_python01.py
class01/homework/JHChoi/hw4_pythonHW_and_math/HW4_python02.py
class01/homework/JHChoi/hw4_pythonHW_and_math/HW4_python03.py
class01/homework/JHChoi/hw4_pythonHW_and_math/HW4_python04.py
class01/homework/JHChoi/hw4_pythonHW_and_math/HW4_python05_not_solved.py

the first of the two types of the homework : Gradient Descent

[Class01 HW#4] python 과제 및 math 실습 [최정호]

---

README.md

01_main_project_README.me uploading

---

class01/homework/TJYoon/hw6/CNN_Batch.py
class01/homework/TJYoon/hw6/CNN_Relu.py
class01/homework/TJYoon/hw6/CNN_noBatch.py
class01/homework/TJYoon/hw6/chest_xray.py
class01/homework/TJYoon/hw6/filter.py

[Class01 HW#6] CNN 실습 [윤태준]

---

class02/homework/JTH119/hw1_led/LED.py
class02/homework/JTH119/hw2_camera/factory.py

[Class02 HW#2] 멀티쓰레딩 카메라 출력 구현

[Class02 HW#2] 멀티쓰레딩 카메라 출력 구현 <정태현>

---

class02/homework/JTH119/hw1_led/LED.py

Class02 과제1 Arduino와 Python을 이용한 LED 제어

Class02 과제1 Arduino와 Python을 이용한 LED 제어 <정태현>

---

class02/homework/kimdoha/hw1/HW1_LED.py
class02/homework/kimdoha/hw2/factory.py

[Class02 HW#2] 멀티쓰레딩 카메라 출력 구현

[Class02 HW#2] 멀티쓰레딩 카메라 출력 구현 <김도하>

---

class02/homework/HTS/hw1/HW1_LED.py
class02/homework/HTS/hw2/factory.py

Class02 hw2 hts

---

class02/homework/HTS/hw1/HW1_LED.py

class02-HTS-hw1

---

class02/homework/EGKo/hw1/led.py
class02/homework/EGKo/hw2/factory.py

[Class02 HW#2] 멀티쓰레딩 카메라 출력 구현 <고의근>

---

class02/homework/JHChoi/hw1/HW1_LED.py

Class02 과제1 Arduino와 Python을 이용한 LED 제어 <최정호> <PR>
